### PR TITLE
Change signature of `get_mut` method on `Outputs` to fix unsafety bug

### LINKED ISSUE #73: get_mut method on Outputs allows for creating multiple refererences as mutable to the same data
The method `get_mut` on `Outputs` has the following signature:
```
pub fn get_mut(&self, i: usize) -> &'a mut [T]
```
Here we are creating a reference as mutable from a reference as immutable. In this way, we can get multiple references as mutable to the same data by passing the same index `i` more than once, violating Rust's aliasing rules.

This is similar to #66, but not fixed by my PR #67, which is why I created a separate issue.

### PR DESCRIPTION
**Pull request by PieterPenninckx**
Fixes #73.

### CODE REVIEW

File: src/buffer.rs [hunk 1]
```diff
@@ -226,7 +226,7 @@ impl<'a, T> Outputs<'a, T> {
     }
 
     /// Mutably access channel at the given index, unchecked
```
Comment (PieterPenninckx) [inline src/buffer.rs]: I'm not sure why the documentation states "unchecked".

Comment (askeksa) [reply src/buffer.rs]: Indeed. With the types in place, there doesn't seem to be anything unchecked about this. Giving an out-of-bounds index will panic, as it should.

Same thing goes for `get` in `Inputs`.
